services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel7_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel7_network
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    command: tail -f /dev/null

  mysql:
    image: mysql:5.7
    container_name: laravel7_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: onlinejobs_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: onlinejobs_user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel7_network
    ports:
      - "3308:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel7_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - laravel7_network
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

networks:
  laravel7_network:
    driver: bridge

